---
- git:
    repo: '{{ git_repository_link }}'
    dest: '{{ repository_location }}'
    clone: yes
    version: master

- replace:
    path: /etc/apache2/sites-enabled/000-default.conf
    regexp: 'DocumentRoot(.)*$'
    replace: 'DocumentRoot {{ default_virtual_host_location }}'
    backup: yes

- name: restart apache2
  service: name=apache2 state=restarted
