---
- git:
    repo: '{{git_project_repository}}'
    dest: '{{repository_location}}'
    force: yes
    clone: yes
    version: master

- template:
    src: templates/000-default.conf.j2
    dest: /etc/apache2/sites-enabled/000-default.conf
    backup: yes

- template:
    src: templates/apache2.conf.j2
    dest: /etc/apache2/apache2.conf
    backup: yes

- name: sudo a2enmod rewrite
  command: a2enmod rewrite
  become: yes


- name: restart apache2
  service: name=apache2 state=restarted

- template:
    src: templates/encrypted/.env.j2
    dest: "{{ repository_location }}/.env"

# Installs package globally
- name: install composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer

# Run this command manually
- composer:
    command: install
    working_dir: "{{repository_location}}"

#TODO:: replace this with copy paste instead of laravel manually generating this
#chdir - is the directory for where to run this command from
- name: generage encryption key
  command: php artisan key:generate chdir={{repository_location}}
  become: yes

- name: migrate laravel
  command: php artisan migrate --force chdir={{repository_location}}

- template:
    src: templates/seeders/AuthClientsTableSeeder.php.j2
    dest: "{{ repository_location }}/database/seeds/AuthClientsTableSeeder.php"

#- name: migrate seed
#  command: php artisan db:seed chdir={{repository_location}}

- name: Install nodeJS
  apt:
    name: nodejs
    state: present

- name: Install npm
  apt:
    name: npm
    state: present

- include_tasks: permissions.yml

#- name: run npm build
#  shell: npm run build
#  args:
#    chdir: "{{ repository_location }}"

