- git:
    repo: '{{ git_repository_link }}'
    dest: '{{ repository_location }}'
    clone: no
    version: master


- name: Update default Apache site
  become: yes
  lineinfile:
    dest=/etc/apache2/sites-enabled/000-default.conf
    regexp="\h* DocumentRoot .*"
    line="        DocumentRoot {{ default_virtual_host_location }}"
  notify:
  - restart apache

- name: Copy sample config file
  command: mv { repository_location }/.env.example { repository_location }/.env creates={ repository_location }/.env
  become: yes

- name: Update laravel .env file
  lineinfile:
    dest={ repository_location }/.env
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
  with_items:
  - {'regexp': "DB_DATABASE=(.)+$", 'line': "DB_DATABASE={ wp_mysql_db }"}
  - {'regexp': "DB_NAME=(.)+$", 'line': "DB_DATABASE={ wp_mysql_user }"}
  - {'regexp': "DB_USER=(.)+$", 'line': "DB_DATABASE={ wp_mysql_password }"}
  become: yes


    ServerAdmin webmaster@localhost
