---
- name: laravel
  hosts: production
  remote_user: root
  become: yes
  gather_facts: False

  roles:
  - load-vars
  - common
  - server
  - server-security
  - php
  - mysql
  - laravel
  - passport