---

#@SEE - UFW module - https://docs.ansible.com/ansible/2.5/modules/ufw_module.html

# Set up UFW - Firewall
- name: Allow everything and enable UFW
  ufw:
    state: enabled
    policy: reject


#  The firewall is currently blocking all connections except for SSH,
#  if you install and configure additional services, you will need to adjust the firewall settings
#  to allow acceptable traffic in. You can learn some common UFW operations in
#  this guide - https://www.digitalocean.com/community/tutorials/ufw-essentials-common-firewall-rules-and-commands.
- name: Enable UFW logging
  ufw:
    logging: on

# Sometimes it is desirable to let the sender know when traffic is
# being denied, rather than simply ignoring it. In these cases, use
# reject instead of deny. In addition, log rejected connections:
- ufw:
    rule: reject
    port: auth
    log: yes

# ufw supports connection rate limiting, which is useful for protecting
# against brute-force login attacks. ufw will deny connections if an IP
# address has attempted to initiate 6 or more connections in the last
# 30 seconds. See  http://www.debian-administration.org/articles/187
# for details. Typical usage is:
- ufw:
    rule: limit
    port: ssh
    proto: tcp

# Allow OpenSSH. (Note that as ufw manages its own state, simply removing
# a rule=allow task can leave those ports exposed. Either use delete=yes
# or a separate state=reset task)
- ufw:
    rule: allow
    name: OpenSSH

- name: Allow all access to tcp port 80 "http://"
  ufw:
    rule: allow
    port: 80
    proto: tcp

- name: Allow all access to tcp port 443 "https://"
  ufw:
    rule: allow
    port: 443
    proto: tcp

- name: Allow All Incoming SMTP
  ufw:
    rule: allow
    port: 25

- name: Allow All Incoming IMAP
  ufw:
    rule: allow
    port: 143

- name: Allow All Incoming POP3
  ufw:
    rule: allow
    port: 110

- name: Allow All Incoming POP3S
  ufw:
    rule: allow
    port: 995