---

- template:
    src: templates/encrypted/.env.j2
    dest: /vagrant/code/.env

#chdir - is the directory for where to run this command from
- name: generage encryption key
  command: php artisan key:generate chdir={{repository_location}}
  become: yes

- name: migrate laravel
  command: php artisan migrate --force chdir={{repository_location}}

- template:
    src: templates/seeders/AuthClientsTableSeeder.php.j2
    dest: /vagrant/code/database/seeds/AuthClientsTableSeeder.php
